const rankerDb = [
    { name: "A*···*Z", score: "20B" },
    { name: "B*···*Y", score: "19.8B" },
    { name: "C*···*X", score: "19.2B" },
    { name: "D*···*W", score: "19B" },
    { name: "E*···*V", score: "18.4B" },
    { name: "F*···*U", score: "18B" },
    { name: "G*···*T", score: "17.6B" },
    { name: "H*···*S", score: "17.2B" },
    { name: "I*···*R", score: "16.9B" },
    { name: "J*···*Q", score: "15B" },
    { name: "K*···*P", score: "14.6B" },
    { name: "L*···*O", score: "14.2B" },
    { name: "M*···*N", score: "13.8B" },
    { name: "N*···*M", score: "13B" },
    { name: "O*···*L", score: "12.9B" },
    { name: "P*···*K", score: "12.6B" },
    { name: "Q*···*J", score: "12.5B" },
    { name: "R*···*I", score: "12B" },
    { name: "S*···*H", score: "11.9B" },
    { name: "T*···*G", score: "11B" },
    { name: "U*···*F", score: "10.8B" },
    { name: "V*···*E", score: "10.4B" },
    { name: "W*···*D", score: "10.3B" },
    { name: "X*···*C", score: "10.1B" },
    { name: "Y*···*B", score: "9.9B" },
    { name: "Z*···*A", score: "9.5B" },
    { name: "A*···*X", score: "9.3B" },
    { name: "B*···*W", score: "9B" },
    { name: "C*···*V", score: "8.9B" },
    { name: "D*···*U", score: "8.7B" }
  ];
  
  export default rankerDb;